export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_KEY = "SET_KEY";
export const SET_POINTS = "SET_POINTS";
export const SET_PAGE = "SET_PAGE";
export const SET_PAGES = "SET_PAGES";
export const SET_IS_FETCHING = "SET_IS_FETCHING";
export const SET_INITIAL_FETCH = "SET_INITIAL_FETCH";
export const SET_HAS_MORE = "SET_HAS_MORE";
export const SET_TWEET_PAGE = "SET_TWEET_PAGE";
export const SET_TWEET_PAGES = "SET_TWEET_PAGES";
export const SET_TWEET_IS_FETCHING = "SET_TWEET_IS_FETCHING";
export const SET_TWEET_INITIAL_FETCH = "SET_TWEET_INITIAL_FETCH";
export const SET_TWEET_HAS_MORE = "SET_TWEET_HAS_MORE";

export const SET_ONLINE_USERS = "SET_ONLINE_USERS";
export const UO_SET_FOLLOWED_BACK = "UO_SET_FOLLOWED_BACK";
export const UO_SET_HAS_FOLLOWINGS = "UO_SET_HAS_FOLLOWINGS";
export const UO_SET_HAS_FOLLOWINGS_TIME = "UO_SET_HAS_FOLLOWINGS_TIME";
export const UO_SET_CHECKING_FOLLOWINGS = "UO_SET_CHECKING_FOLLOWINGS";
export const UO_SET_CHECKING_FOLLOWED_BACK = "UO_SET_CHECKING_FOLLOWED_BACK";
export const UO_SET_CHECKING_NOT_FOLLOWED_BACK =
  "UO_SET_CHECKING_NOT_FOLLOWED_BACK";
export const UO_SET_NOT_FOLLOWING_BACK = "UO_SET_NOT_FOLLOWING_BACK";
export const UO_SET_GETTING_USERS = "UO_SET_GETTING_USERS";
export const UO_SET_LINEAR_PROGRESS_BAR_COMPLETED =
  "UO_SET_LINEAR_PROGRESS_BAR_COMPLETED";
export const UO_SET_IS_UNFOLLOWING = "UO_SET_IS_UNFOLLOWING";
export const UO_GET_ERRORS = "UO_GET_ERRORS";
export const UO_CLEAR_ERRORS = "UO_CLEAR_ERRORS";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const MARK_AS_READ = "MARK_AS_READ";

export const SNACKBAR_OPEN = "SNACKBAR_OPEN";
export const SNACKBAR_MESSAGE = "SNACKBAR_MESSAGE";
export const SNACKBAR_VARIANT = "SNACKBAR_VARIANT";
export const SNACKBAR_VERTICAL = "SNACKBAR_VERTICAL";
export const SNACKBAR_HORIZONTAL = "SNACKBAR_HORIZONTAL";

export const SET_USERS_PAGE = "SET_USERS_PAGE";
export const SET_USERS = "SET_USERS";
export const SET_USERS_INITIAL_FETCH = "SET_USERS_INITIAL_FETCH";
export const SET_USERS_IS_FETCHING = "SET_USERS_IS_FETCHING";
export const SET_USERS_HAS_MORE = "SET_USERS_HAS_MORE";
