export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_KEY = "SET_KEY";
export const SET_POINTS = "SET_POINTS";
export const SET_PAGE = "SET_PAGE";
export const SET_PAGES = "SET_PAGES";
export const SET_IS_FETCHING = "SET_IS_FETCHING";
export const SET_INITIAL_FETCH = "SET_INITIAL_FETCH";
export const SET_HAS_MORE = "SET_HAS_MORE";
export const SHARED_TWEETS_COUNT = "SHARED_TWEETS_COUNT";
export const ADD_STATUS = "ADD_STATUS";
export const SET_TWEET_PAGE = "SET_TWEET_PAGE";
export const SET_TWEET_PAGES = "SET_TWEET_PAGES";
export const SET_TWEET_IS_FETCHING = "SET_TWEET_IS_FETCHING";
export const SET_TWEET_INITIAL_FETCH = "SET_TWEET_INITIAL_FETCH";
export const SET_TWEET_HAS_MORE = "SET_TWEET_HAS_MORE";

export const SNACKBAR_OPEN = "SNACKBAR_OPEN";
export const SNACKBAR_MESSAGE = "SNACKBAR_MESSAGE";
export const SNACKBAR_VARIANT = "SNACKBAR_VARIANT";
export const SNACKBAR_VERTICAL = "SNACKBAR_VERTICAL";
export const SNACKBAR_HORIZONTAL = "SNACKBAR_HORIZONTAL";

export const SET_USERS_PAGE = "SET_USERS_PAGE";
export const SET_USERS = "SET_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_UNFOLLOW_USER = "UPDATE_UNFOLLOW_USER";
export const SET_USERS_INITIAL_FETCH = "SET_USERS_INITIAL_FETCH";
export const SET_USERS_IS_FETCHING = "SET_USERS_IS_FETCHING";
export const SET_USERS_HAS_MORE = "SET_USERS_HAS_MORE";
export const REFRESH_ONLINE = "REFRESH_ONLINE";
export const REFRESH_TWEETS = "REFRESH_TWEETS";
export const REFRESH_PROFILE = "REFRESH_PROFILE";

export const ENQUEUE_SNACKBAR = "ENQUEUE_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const REMOVE_SNACKBAR = "REMOVE_SNACKBAR";


export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
