export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_TOTAL_GAINED = "SET_TOTAL_GAINED";
export const SET_FOLLOWINGS = "SET_FOLLOWINGS";
export const SET_FOLLOWED_BACK = "SET_FOLLOWED_BACK";
export const SET_LINEAR_PROGRESS_BAR_COMPLETED =
  "SET_LINEAR_PROGRESS_BAR_COMPLETED";
export const SET_STATS = "SET_STATS";
export const SET_HAS_FOLLOWINGS = "SET_HAS_FOLLOWINGS";
export const SET_HAS_FOLLOWINGS_TIME = "SET_HAS_FOLLOWINGS_TIME";
export const SET_CHECKING_FOLLOWINGS = "SET_CHECKING_FOLLOWINGS";
export const SET_CHECKING_FOLLOWED_BACK = "SET_CHECKING_FOLLOWED_BACK";
export const SET_IS_FOLLOWING = "SET_IS_FOLLOWING";
export const SET_IS_UNFOLLOWING = "SET_IS_UNFOLLOWING";
